name: Andriod Build APK

on: 
  push:
    branches:
     - main

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checout@v2

       - name: Set up JDK 17
         uses: action/setup-java@v2
         with:
             java-version: '17'

       - name: Build APK
         run: ./gradle assembleRelease

       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
            name: meal-app-apk
            path: app/build/outputs/apk/release/app-release.apk
      
         
        
    
